### ISSUE TITLE
On resubmission file went to committed

### ISSUE THREAD

**Issue by jcowey** [papyri/sosol#128]
record worked on (probably under a different editor/publications/number) was submitted. Appeared in DCLP board. Vote given was "Return-Striaght-to-Sender" That worked. Submitter made corrections and resubmitted. 

The file can now be seen on her users branch as "committed"
File: http://dev.papyri.info/editor/publications/65779
User: http://papyri.info/editor/users/lavavilla

This is obviously not what we want to happen. The resubmitted file should appear on the board again.

**Comment by jcowey** [comment]
We tried this again.

http://dev.papyri.info/editor/publications/65790
was opened, changes made and submitted

http://dev.papyri.info/editor/publications/65791/dclp_meta_identifiers/149287/edit
was given two Return-to-Sender votes.

The file went back to the submitter
where it was

http://dev.papyri.info/editor/publications/65790

again.
It was resubmitted and went to the committed section.

**Comment by jcowey** [comment]
Reminds me a little bit of https://github.com/papyri/sosol/issues/62

**Comment by ryanfb** [comment]
I suspect there's something going on with the status change or checking logic during this workflow. I've deployed a new version that probably won't fix the issue yet but has a whole lot of additional logging that should help me diagnose/fix the issue, if you can test the submit/reject/submit workflow again and give me the publication ID.

**Comment by jcowey** [comment]
http://dev.papyri.info/editor/publications/65796
submitted
http://dev.papyri.info/editor/publications/65797
Return-straight-to-Sender vote
made it go back to the submitter
A change was made and the file (65796, of course) resubmitted.

It landed in Giuditta Mirizio's (http://dev.papyri.info/editor/users/giuditta%20mirizio) committed section again. 

So apparently still not working properly. The file on being resubmitted should appear on the DCLP board again.

**Comment by ryanfb** [comment]
Think this bug should be fixed by https://github.com/sosol/sosol/commit/9debc44b7e75b27e1fc32cbcab9d45045b55f14c. Now live, and tested with http://dev.papyri.info/editor/publications/65802, which was submitted, rejected, resubmitted as: http://dev.papyri.info/editor/publications/65804
